import csv
from collections import defaultdict
import matplotlib.pyplot as plt

TOP_N_PER_CATEGORY = 6

# load the data from the CSV file generated by spark_pipeline.py
rows = []
with open("top_hashtags.csv", "r") as f:
    reader = csv.DictReader(f)
    for row in reader:
        rows.append({
            "hashtag": row["hashtag"],
            "category": row["category"],
            "count": int(row["total_count"])
        })
# group rows by category
by_category = defaultdict(list)
for r in rows:
    by_category[r["category"]].append(r)

for cat in by_category:
    by_category[cat] = sorted(by_category[cat], key=lambda x: x["count"], reverse=True)[:TOP_N_PER_CATEGORY]

# compute the min and max counts across all categories for color shading
categories = sorted(by_category.keys())
n_categories = len(categories)
max_count = max(r["count"] for items in by_category.values() for r in items)
min_count = min(r["count"] for items in by_category.values() for r in items)

# Set up a color map for categories, and a function to shade bubbles based on count
cmap = plt.cm.get_cmap("tab20", n_categories)
category_base_colors = {cat: cmap(i) for i, cat in enumerate(categories)}

def shade_for_count(base_rgba, count):
    frac = (count - min_count) / max(1, (max_count - min_count))
    darkness = 0.5 + 0.5 * frac
    r, g, b, a = base_rgba
    return (r * darkness, g * darkness, b * darkness, 0.9)

# Define bubble size and spacing parameters
import math

n_categories = len(categories)
max_count = max(r["count"] for items in by_category.values() for r in items)
min_count = min(r["count"] for items in by_category.values() for r in items)

cmap = plt.cm.get_cmap("tab20", n_categories)
category_base_colors = {cat: cmap(i) for i, cat in enumerate(categories)}

# change the darkness of the base color based on the count, so higher counts are darker
def shade_for_count(base_rgba, count):
    frac = (count - min_count) / max(1, (max_count - min_count))
    darkness = 0.5 + 0.5 * frac
    r, g, b, a = base_rgba
    return (r * darkness, g * darkness, b * darkness, 0.9)

BUBBLE_RADIUS = 0.72  # base/minimum radius, used for short words
bubbles_per_row = 3
BUBBLE_GAP = 0.5

def radius_for_text(hashtag, fontsize):
    # Estimate the radius needed to fit the text inside the bubble, based on empirical scaling
    text_len = len(hashtag)
    est_width_units = text_len * fontsize * 0.011  # empirical scale factor
    needed_radius = est_width_units / 2 + 0.12  # half width + small padding
    return max(BUBBLE_RADIUS, needed_radius)

def fontsize_for_text(hashtag):
    text_len = len(hashtag)
    if text_len <= 6:
        return 10.5
    elif text_len <= 9:
        return 9
    elif text_len <= 12:
        return 8
    else:
        return 7

# Precompute font size and radius for every hashtag up front
for cat in categories:
    for item in by_category[cat]:
        item["_fontsize"] = fontsize_for_text(item["hashtag"])
        item["_radius"] = radius_for_text(item["hashtag"], item["_fontsize"])

# Precompute each category's block size using the LARGEST bubble in that category,
# so the grid spacing is uniform within a panel (avoids uneven overlapping grids)
block_sizes = {}
panel_bubble_radius = {}
for cat in categories:
    items = by_category[cat]
    max_r = max(item["_radius"] for item in items)
    panel_bubble_radius[cat] = max_r
    spacing = max_r * 2 + BUBBLE_GAP
    n_items = len(items)
    item_rows = -(-n_items // bubbles_per_row)
    block_w = min(n_items, bubbles_per_row) * spacing
    block_h = item_rows * spacing
    block_sizes[cat] = (block_w, block_h)

# Place most categories around a ring; place smaller/fewer categories closer to the
# center to fill the middle instead of leaving it empty (no donut hole).

sorted_cats = sorted(categories, key=lambda c: -(block_sizes[c][0] * block_sizes[c][1]))

RING_RADIUS = 9.5
INNER_RADIUS = 3.2

category_center = {}
outer_count = max(1, n_categories - 2)  # reserve up to 2 smallest for the center
outer_cats = sorted_cats[:outer_count]
inner_cats = sorted_cats[outer_count:]

for i, cat in enumerate(outer_cats):
    angle = 2 * math.pi * i / len(outer_cats)
    category_center[cat] = (RING_RADIUS * math.cos(angle), RING_RADIUS * math.sin(angle))

# Inner categories: stack near the true center, offset so they don't overlap each other
for i, cat in enumerate(inner_cats):
    angle = 2 * math.pi * i / max(1, len(inner_cats))
    r = INNER_RADIUS if len(inner_cats) > 1 else 0
    category_center[cat] = (r * math.cos(angle), r * math.sin(angle))

fig, ax = plt.subplots(figsize=(18, 16))

for cat in categories:
    items = by_category[cat]
    block_w, block_h = block_sizes[cat]
    cx, cy = category_center[cat]
    spacing = panel_bubble_radius[cat] * 2 + BUBBLE_GAP

    start_x = cx - block_w / 2 + spacing / 2
    start_y = cy + block_h / 2 - spacing / 2

    for i, item in enumerate(items):
        r_i = i // bubbles_per_row
        c_i = i % bubbles_per_row
        bx = start_x + c_i * spacing
        by = start_y - r_i * spacing

        color = shade_for_count(category_base_colors[cat], item["count"])
        circle = plt.Circle((bx, by), item["_radius"], color=color, edgecolor="black", linewidth=0.7, zorder=3)
        ax.add_patch(circle)

        ax.text(bx, by, item["hashtag"], fontsize=item["_fontsize"], ha="center", va="center",
                 weight="bold", color="white", zorder=4)

    label_y = start_y + spacing * 0.9
    ax.text(cx, label_y, cat.upper(),
             fontsize=13, ha="center", weight="bold", color=category_base_colors[cat], zorder=4)

ax.set_aspect("equal")
ax.axis("off")
ax.autoscale_view()
ax.margins(0.12)

fig.suptitle("Top Hashtags per Category\n(darker bubble = higher post count)", fontsize=17, y=0.97)

plt.tight_layout(rect=[0, 0, 1, 0.94])
plt.savefig("hashtag_clusters.png", dpi=150, bbox_inches="tight")
plt.show()

print("Cluster plot saved to hashtag_clusters.png")